apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dnsmadeeasy.name" . }}
  labels:
    {{ include "dnsmadeeasy.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: dnsmadeeasy-webhook
      app.kubernetes.io/instance: {{ include "dnsmadeeasy.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dnsmadeeasy-webhook
        app.kubernetes.io/instance: {{ include "dnsmadeeasy.name" . }}
    spec:
      
      serviceAccountName: {{ include "dnsmadeeasy.name" . }}
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: {{ include "dnsmadeeasy.name" . }}
          image: "harbor.eencloud.com/infrastructure/dnsmadeeasy-webhook:v1.0.0"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
            - --secure-port={{ .Values.listeningPort }}
          env:
            - name: "GROUP_NAME"
              value: {{ .Values.groupName | quote }}
          ports:
            - name: https
              containerPort: {{ .Values.listeningPort }}
              protocol: TCP
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: certs
          secret:
            secretName: {{ include "dnsmadeeasy.name" . }}-webhook-tls
