apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dnsmadeeasy.name" . }}
  labels:
    {{ include "dnsmadeeasy.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: dnsmadeeasy-webhook
      app.kubernetes.io/instance: {{ include "dnsmadeeasy.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dnsmadeeasy-webhook
        app.kubernetes.io/instance: {{ include "dnsmadeeasy.name" . }}
    spec:
      serviceAccountName: {{ include "dnsmadeeasy.names.serviceAccountName" . }}
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: {{ include "dnsmadeeasy.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --v=6
            - --secure-port={{ .Values.listeningPort }}
            - --cert-dir=/tls
          env:
            - name: "GROUP_NAME"
              value: {{ .Values.groupName | quote }}
          ports:
            - name: https
              containerPort: {{ .Values.listeningPort }}
              protocol: TCP
          volumeMounts:
            - name: certs
              mountPath: /tls
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          # startupProbe:
          #   failureThreshold: 30
          #   httpGet:
          #     path: /healthz
          #     port: https
          #     scheme: HTTPS
          #   initialDelaySeconds: 0
          #   periodSeconds: 5
          #   timeoutSeconds: 1
      volumes:
        - name: certs
          emptyDir: {}
