{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dnsmadeeasy.names.serviceAccountName" . }}
  labels:
    {{ include "dnsmadeeasy.labels" . | nindent 4 }}
{{- end }}