apiVersion: v1
kind: Service
metadata:
  name: {{ include "dnsmadeeasy.name" . }}
  labels:
    {{ include "dnsmadeeasy.labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.listeningPort }}
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: dnsmadeeasy-webhook
    app.kubernetes.io/instance: {{ include "dnsmadeeasy.name" . }}
