apiVersion: v1
kind: Service
metadata:
  name: {{ include "dnsmadeeasy.name" . }}
  labels:
{{ include "dnsmadeeasy.labels" . | nindent 4 }}
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 4443
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: dnsmadeeasy-webhook
    app.kubernetes.io/instance: {{ include "dnsmadeeasy.name" . }}
